### ISSUE TITLE
Sample app V2

### ISSUE THREAD

**Issue by birkir** [ueno-llc/ueno-cra-starter#3]
Lets be more creative with the sample app.

 - Add footer
 - Add a gsap animation
 - Page transition
 - Retina images
 - Maybe some kind of design?
 - Update favicon
 - More default components, input/etc.
 - Ship with optional server api (contentful, headless wordpress or custom backend)

**Comment by jeremybarbet** [comment]
Good idea!

I can work on some gsap animations/page transition.

What about using our ueno-ui also? To get all forms, retina images components? but could be a mess to add somehow.

**Comment by birkir** [comment]
That would be fantastic! It should be fairly easy to add external css, cra must have a way to add bootstrap for example, so either we modify ueno-ui to meet that requirement or fix something in ueno-cra

**Comment by jeremybarbet** [comment]
I'll start to work on few things (gsap), I'll add them to the template directory directly, does it sound good?
